name: ml-basic

channels:
  - conda-forge

dependencies:
  - python=3.10
  - pip

  - pip:
    - ploomber
    - pandas
    - scikit-learn
    - pyarrow
    - sklearn-evaluation
    - jupyter
    # - google-cloud-storage
